### ISSUE TITLE
Normalization of Junction reads.

### ISSUE THREAD

**Issue by manensinegi** [YumaIshigami/irscalc#4]
Hi,
I really liked the script. Well written and provides a lot of information. I would like to know whether the script normalizes the EI, IE, and EE junction counts (are they raw counts or CPM). IRS value doesn't say if there is a change in Pre-mRNA accumulation, or a decrease in mRNA, or both, which can be the case for some splicing factor mutants. CPM values of these junctions can tell that information. 

Kindly let me know if normalization for the junction counts can be done within the script.

Thank you
Best wishes
Manendra Singh Negi

**Comment by YumaIshigami** [comment]
Hi Manendra,

It is recommended to obtain differential gene expression with specifically designed software such as FeatureCounts - EdgeR.

As you pointed out, this script only obtains the ratio between the EI, IE, and EE junctions for statistical analysis.
The raw count of counts is exported into the raw data in the columns right to the "trepseme" column and left to the "irs_con1" column.
You can apply this data to software that calculates differential expression data based on counts (like EdgeR).
In this case, normalization is done on the side of that software based on the total counts.
In most cases, softwares that use read count as input utilize external softwares like FeatureCounts or HTSeq-count to obtain the read count for each gene so that the junction count may serve the same function.
For this reason, I consider it inappropriate to apply any normalization method for transcripts such as FPKM, CPM, or TPM in this script.
